FROM rustlang/rust:nightly-buster as builder

RUN USER=root cargo new --bin governance_poller
WORKDIR /governance_poller

# copy over your manifests
COPY ./Cargo.toml ./Cargo.toml

# this build step will cache your dependencies
RUN cargo build --release
RUN rm src/*.rs

# copy your source tree
COPY ./src ./src
#COPY ./contracts ./contracts
#COPY . .

RUN cargo build --release --bin user_external_addresses

FROM debian:buster-slim

RUN apt-get update && \
    apt-get --assume-yes install \
        make \
        libpq5 \
        libpq-dev \
        -qqy \
        --no-install-recommends
RUN apt-get update && apt-get -y install ca-certificates libssl-dev && rm -rf /var/lib/apt/lists/*

COPY --from=builder /governance_poller/target/release/user_external_addresses /governance_poller/user_external_addresses
WORKDIR /governance_poller/
EXPOSE 8088


CMD ["/governance_poller/user_external_addresses"]
